-----1. CREATE A TABLE IN DATABASE---

CREATE TABLE P1 (STUD_ID INTEGER,STUD_NAME VARCHAR(24),STUD_MARKS NUMBER(20));

CREATE TABLE P2 (SUB_ID INTEGER, SUB_NAME VARCHAR(20), SUB_TEACHER VARCHAR(20));

-----2. DESCRIBE THE STRUCTURE OF THE TABLE----

DESC P1;
DESC P2;

----3. INSERT THE ROW WISE RECORD INTO THE TABLE---

INSERT INTO P1 VALUES (1,'TEJAS',45);
  ---MULTIPLE ROWS AT A TIME
  INSERT ALL 
  INTO P1 VALUES (2, 'YASH', 55)
  INTO P1 VALUES (3, 'SHOBHA', 90)
  INTO P1 VALUES (4, 'VIJAY', 100)
  SELECT * FROM P1; 
  
  INSERT ALL 
  INTO P1 VALUES (101, 'DSA','PROF.BENKE')
  INTO P1 VALUES (102, 'OOP', 'PROF.PATOLE')
  INTO P1 VALUES (103, 'DELD', 'DR.AUTADE')
  SELECT * FROM P2;
  
  ------4. DISPLAY THE RECORD USING SELECT ---
  
  SELECT * FROM P1 ;
  
  --WITH CONDITIONS--
  
  SELECT STUD_NAME FROM P1;
  SELECT STUD_ID,STUD_MARKS FROM P1;
  SELECT STUD_ID FROM P1 WHERE stud_marks>=50;
  SELECT STUD_ID FROM P1 WHERE (stud_marks>=50);
  SELECT STUD_ID, STUD_NAME FROM P1 WHERE STUD_MARKS = 30;
  SELECT STUD_ID, STUD_NAME FROM P1 WHERE STUD_MARKS<60;
    SELECT STUD_ID, STUD_NAME FROM P1 WHERE STUD_NAME LIKE 'Y%'; --starting with specific letter--
        SELECT STUD_ID, STUD_NAME FROM P1 WHERE STUD_NAME LIKE '%Y';--ending with specific letter--
            SELECT STUD_ID, STUD_NAME FROM P1 WHERE STUD_NAME LIKE '%S%'; ---anywhere in the name--case sensitive
            SELECT STUD_ID, STUD_NAME FROM P1 WHERE STUD_NAME LIKE '%V%JA%';
            SELECT STUD_ID, STUD_NAME FROM P1 WHERE STUD_NAME LIKE 'Y%H'; --start and end--
            SELECT STUD_ID, STUD_NAME FROM P1 WHERE REGEXP_LIKE(STUD_NAME, '^[AEIOU]'); --Names starting with any of these vowels--
            SELECT STUD_ID, STUD_NAME FROM P1 WHERE STUD_NAME NOT LIKE 'Y%'; ---NOT STARTING WITH SPECIFIC--
            SELECT STUD_ID, STUD_NAME FROM P1 WHERE REGEXP_LIKE(STUD_NAME,'^[A-Za-z]+$'); --gives the names that contains only alphabets--
            SELECT STUD_ID, STUD_NAME FROM P1 WHERE LENGTH(STUD_NAME)=5; --length of thenmae--
            SELECT STUD_ID, STUD_NAME FROM P1 WHERE REGEXP_LIKE(STUD_NAME, '^[a-z]'); --gives names that start with small case--
    
    ------SELECT BY ORDERING THE DATA AND DISPLAYING SPECIFIC RECORD------
    
    SELECT * FROM P1;
    
    SELECT STUD_NAME, LENGTH(STUD_NAME) AS LEN FROM P1 ORDER BY stud_name;
    SELECT STUD_NAME FROM P1 ORDER BY stud_name;
    SELECT STUD_NAME, LENGTH(STUD_NAME) AS LEN FROM P1 ORDER BY stud_name WHERE ROWNUM=1;
    
    
        
        
-------- 5. UPDATE the Table--
    
    UPDATE P1 SET stud_marks=70 WHERE STUD_NAME='YASH';
    SELECT * FROM P1;
    
 ------6. INSERT INTO TABLE VALUES-- --
 
 INSERT INTO P2 SELECT * FROM P1; 
 SELECT * FROM P2;

-----7. DROP --

CREATE TABLE P3 (SRNU INTEGER, NAMESOF VARCHAR(10));
SELECT * FROM P3;
INSERT INTO P3 VALUES (1,'NAZIA');
UPDATE p3 SET SRNU=233;
DROP TABLE P3;

--7. TRUNCATE-------

TRUNCATE TABLE P3;

----8.DELETE------
DELETE P3;
DELETE 

    

  

